server:
  port: 8000

spring:
  ai:
    ollama:
      base-url: http://localhost:11434
  application:
    name: embabel-database-server
  config:
    import: "optional:classpath:prompts.yml"
  http:
    client:
      connect-timeout: 30s
      read-timeout: 240s #increased to cater for CPU-based ollama  
  output:
    ansi:
      enabled: ALWAYS
#  profiles:
#    active: ollama

springdoc:
  api-docs:
    path: /api-docs        

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr([%t]){magenta} %clr(%-5level) %clr(%logger{0}){cyan} %clr(-){faint} %msg%n"          

embabel:
  llm-operations:
    prompts:
      default-timeout: PT1M
  models:
    defaultLlm: llama3.1:8b
    # defaultEmbeddingModel: nomic-embed-text:latest

aws:
  region: us-east-1
  accesKeyId: your-key-here
  secretAccessKey: your-secret-key-here

