server:
  port: 8000

spring:
  ai:
    model:
      chat: none
  application:
    name: embabel-database-server
  config:
    import: "optional:classpath:prompts.yml"

springdoc:
  api-docs:
    path: /api-docs        

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr([%t]){magenta} %clr(%-5level) %clr(%logger{0}){cyan} %clr(-){faint} %msg%n"          

embabel:
  models:
    defaultLlm: us.anthropic.claude-3-5-sonnet-20240620-v1:0

